name: ADR
description: Record an architectural decision about the project
title: "[ADR]: "
labels: ["docs: adr"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Record an architectural decision about the project
  - type: markdown
    attributes:
      value: |
        **Example** [Wiki ADR](https://github.com/HHS/grants-api/issues/30)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: 1-2 sentence summary of the decision that needs to be made
    validations:
      required: true
  - type: textarea
    id: approvers
    attributes:
      label: Approvers
      description: List individuals or groups that must approve this decision before the ADR is accepted
    validations:
      required: false
  - type: textarea
    id: options
    attributes:
      label: Options
      description: List of options to evaluate
    validations:
      required: false
  - type: textarea
    id: decision-criteria
    attributes:
      label: Decision Criteria
      description: List of decision criteria to evaluate
    validations:
      required: false
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Leave the following acceptance criteria unchecked when the ticket is created then mark them as completed as you meet each criterion with the ADR
      options:
        - label: The ADR is drafted and stored in `documentation/decisions/adr`
        - label: The ADR is included in the necessary table of contents in the ADR/decision folder
        - label: The ADR describes the drivers and pros and cons of the decision
        - label: The ADR has been reviewed and approved by the internal team
        - label: The ADR satisfies requirements that are outlined in the ADR template
    validations:
      required: true
