name: Lint - Create milestone for 10k

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  create-milestone:
    name: Create milestone for 10k issue
    # only run this if issue has the 'bug' label and isn't assigned to a milestone
    if: ${{ contains(github.event.issue.labels.*.name, 'bug') && (! github.event.issue.milestone) }}
    runs-on: ubuntu-latest

    # set permissions of automatically created GitHub token to issue: write
    permissions:
      issues: write
    env:
     GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3
      - name: Create the milestone
        run: |
          gh api \
            --method POST \
            /repos/widal001/project-demo/milestones \
            -f title='${{ github.event.issue.title }}'
      - name: Assign issue to milestone
        run: |
          gh issue edit ${{ github.event.issue.number }} --milestone '${{ github.event.issue.title }}' --repo widal001/project-demo
