name: Lint - Create milestone for 10k

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  create-milestone:
    name: Create milestone for 10k issue
    if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
    runs-on: ubuntu-latest

    # set permissions of automatically created GitHub token to issue: write
    permissions:
      issues: write
    env:
     GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3
      - name: Print issue name
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/widal001/project-demo/milestones \
            -f title='${{ github.event.issue.title }}'
            -f state='open'
