name: Lint - Create milestone for 10k

on:
  issues:
    types: [opened, edited, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  create-milestone:
    name: Create milestone for 10k issue
    # only run this if issue has the 'deliverable: 10k' label and isn't assigned to a milestone
    if: "${{ contains(github.event.issue.labels.*.name, 'deliverable: 10k ft') && (! github.event.issue.milestone) }}"
    runs-on: ubuntu-latest

    # set permissions of automatically created GitHub token to issue: write
    permissions:
      issues: write
    env:
     GH_TOKEN: ${{ github.token }}
     REPO: ${{ github.repository }}
     ISSUE_TITLE: ${{ github.event.issue.title }}
     ISSUE_NUMBER: ${{ github.event.issue.number }}

    steps:
      - uses: actions/checkout@v3
      - name: Create the milestone
        run: |
          gh api \
            --method POST \
            /repos/$REPO/milestones \
            -f title="${ISSUE_TITLE}"
      - name: Assign issue to milestone
        run: |
          gh issue edit $ISSUE_NUMBER --milestone "${ISSUE_TITLE}" --repo $REPO
